-- linkedin_drafts table
-- Stores LinkedIn post drafts generated by linkedin-writer.skill.ts
-- Approval flow: Draft → Approved / Skipped / Edited via #organic-agent Slack buttons

CREATE TABLE IF NOT EXISTS linkedin_drafts (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  target          TEXT        NOT NULL CHECK (target IN ('neil-personal', 'fsiq-company')),
  topic           TEXT        NOT NULL,
  post_text       TEXT        NOT NULL,
  status          TEXT        NOT NULL DEFAULT 'Draft'
                              CHECK (status IN ('Draft', 'Approved', 'Skipped', 'Edited')),
  slack_ts        TEXT,
  slack_channel   TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on row changes
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'linkedin_drafts_updated_at'
  ) THEN
    CREATE TRIGGER linkedin_drafts_updated_at
      BEFORE UPDATE ON linkedin_drafts
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;
